### ISSUE TITLE
Dont know if .17 fixed this but terminal isnt placable

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [Astavie/ThermalLogistics#17] opened 2019-02-22 19:35 UTC
Is it not a block because it is not placable. Yes this is the block one

**Comment by Astavie** [comment] 2019-02-22 19:37
What version? versions 0.1-x need the terminal to be placed on a duct

**Comment by hron84** [comment] 2019-03-12 00:49
You should not make this as a strong requirement. What if I only can place ducts later? Will the terminal drop if I dismantle the duct behind it (for example replacing it with a better one)? Yes, terminal is only usable if there is a duct connected but terminal block itself should not bind placement permission to ducts.

**Comment by Astavie** [comment] 2019-03-12 06:27
You're forgetting that in 0.2 terminals can be placed wherever now

**Comment by Astavie** [comment] 2019-04-05 08:01
Interpreting as duplicate of #7

**Closed as completed** 2019-04-05 08:00 UTC
Labels: duplicate
