### ISSUE TITLE
Terminal causes crash because of enchanted book in the network

### ISSUE THREAD

**Issue by Kreestijan** [Astavie/ThermalLogistics#23] opened 2019-04-14 19:28 UTC
If there's an enchanted book that exceeds usual vanilla enchants the terminal will crash upon opening. I had a book with Unbreaking IV in a chest that was connected to the terminal via ducts.

https://paste.dimdev.org/ojuresuqip.mccrash

**Comment by Astavie** [comment] 2019-04-19 11:49
This might already be fixed in version 0.2-18, and this crash log is still using version 0.2-17

**Comment by Astavie** [comment] 2019-04-19 14:04
Marking as duplicate of #20

**Closed as completed by Astavie** 2019-04-19 14:04 UTC
Labels: duplicate
